# Generated by Django 3.2.9 on 2021-11-16 04:42

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synrateuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='synrateuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='synrateuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с данным именем уже существует.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
